### ISSUE TITLE
Decide the dates for start and close of CFP

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2020-tasks#1]

**Comment by anistark** [comment]
Dates as decided on call:

|  Date | Action  |
| --- | --- |
| March 12th | CFP open |
| July 1st | CFP closes |
| August 15th | Schedule release |

**Comment by rayandas** [comment]
Updated dates:

CFP open: Apr 24
CFP closes: Aug 14 
Schedule release: Sept 1

**Comment by sayanchowdhury** [comment]
We've the CFP opened and can close this issue now.
