### ISSUE TITLE
Create reception, registration and sponsors page

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2020-tasks#102]
## Main volunteers
* Abhishek, Sayan, Sanchit, Ram, Jatin

## TODO
  - Create Reception & registration page
  - Add Sponsors
  - Create Expo booth for each sponsors
    - do the initial setup
    - Setup a call for walkthrough of expo for each sponsor
    - Create zulip channel for each sponsors
    - Generate complementary passes for sponsors
  - Make sure all the sponsorship get fulfilled 

## Deadlines
- Get reception and registration, sponsors setup,, expo on hopinto by Friday i.e.25th Sept 10:00 PM
- if logo not there, put the dummy assets

**Comment by inovizz** [comment]
I'll create Sponsor Booths by this weekend and the main event as well once Alex is available.
