### ISSUE TITLE
Prepare Attendees registration in hopinto aka magic link

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2020-tasks#104]
One Event is up
- Nabarun to work with Sanchit and Abhishek to prepare the swag kit
- Nabarun to get attendee csv from townscript, sayan needs to provide
  - Nabarun to format csv in hopinto attendee format
  - Generate magic link

## Deadline
- Sunday 27th September

**Comment by inovizz** [comment]
Is there anything needed from me on this?
