### ISSUE TITLE
Create email templates for conference and workshop days

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2020-tasks#105]
## Content team needs to
  - create template using liquid template for 
     - Welcome message
       - Swag kit will be on badge site (check with nabarun)
       - ppg docs needs to be attached
       - Calender invite needs to be added (check with nabarun)
     - Day 1
     - Day 2
     - DevSprint
     - Workshop
     - End email for talk feedback 
     - Find a useful way to get feedback
        - May be use pool to create feedback

## Deadline
- 27th Sept, 2020 i.e sunday

**Comment by vipulgupta2048** [comment]
Roger all!

**Comment by vipulgupta2048** [comment]
> Find a useful way to get feedback

- Hopin Polls 
    - ~~Polls, happen after every session started by session moderators when the previous session is completed. Each poll will have a question format like below~~ Won't work as Polls in Hopin are not stage-specific so this can't happen.

    ```markdown
    > How was Pythons session #128: Talking to the snakes?
    ```

- Make a form for general conference feedback, talking about
0. Content of the talks and tracks (most important)
1. Audio/Video/platform stuff
2. Accessiblity and diversity
3. PPG/Social Media 
4. more questions ....

**Comment by vipulgupta2048** [comment]
Email templates being created by @Sc0rpi0n101

**Comment by vipulgupta2048** [comment]
Completed @raukadah 
https://www.notion.so/pyconindia/Email-Templates-for-Hopin-5b8256a0a48648019cf74c583d93ab70

**Comment by Sc0rpi0n101** [comment]
> Completed @raukadah
> https://www.notion.so/pyconindia/Email-Templates-for-Hopin-5b8256a0a48648019cf74c583d93ab70

All the mails have links to zulip and stuff that need to be added. Please make sure to add all the required links before sending them.
