### ISSUE TITLE
Create Zulip channel for conference, workshop and devsprint days

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2020-tasks#106]
## Need to create channels
 -> Track based Channels
     -> Stage based channels where speaker will hangs
-> Make it stream based on talks to ask questiom
     -> keynote channel will be merged with blr stage
     -> Workshop specific seperate channel
     -> Devsprint project wise channel
   -> Infomation channels
      -> Announcement Channel (Read Only)
         -> Need a list of owners to post announcements
         -> lightening talks announcements 
     -> Help Desk (all queries, reps from all team will be there)
-> Speaker lounge (Private)
-> Sponsors based channels
   -> Need seperate(s) channels for each sponsors
   -> Sponsors coordination channel 
        -> Zulip & whatsapp

## TODO
 - @amolkahat needs to do the work
 - Need admin access from Ani or Abhishek

## List of streams:

- [x] Added 2020/workshop stream 

- [x] 2020/Hyderabad

- [x] 2020/volunteers

- [x] 2020/announcements

- [x] 2020/sponsor-coordination

- [x] 2020/speaker-lounge

- [x] 2020/Pune

- [x] 2020/Chennai 

- [x] 2020/Bangalore

- [x] 2020/helpdesk

## Timeline
- Get it done by Thursday i.e.24th Sept, 2020

**Comment by anistark** [comment]
For Devsprint, I had created a `#2020/devsprint` as a common stream.

There can also be individual streams for each project, like `#2020/devsprint/<project_slug>` or something like that.
Or can be different topic for each project in same stream (`#2020/devsprint`) as well.

Leave that decision to @amolkahat.

**Comment by amolkahat** [comment]
All the above channels are created. Closing.

**Comment by amolkahat** [comment]
![2020_substreams_1](https://user-images.githubusercontent.com/10204255/94287452-f251f200-ff73-11ea-8a6e-23808d0c9590.jpg)

**Comment by anistark** [comment]
@amolkahat I think you've added some other "Ani" to the private streams 😛 

I'm "Anirudha" on Zulip.
