### ISSUE TITLE
Execute job fair

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2020-tasks#112]
## Plan
For each company participating in job fair
- we will create a separate expo booth(Job fair booth) for each of them.
- Company will share their slides and company representative will there
- Attendees will be comes and register there via google form or their website (for job registering )and submit the resume.
- Once shortlisted, they will perform 1:1 meeting with them for initial screening via private sessions.
- Sessions can be on hopin or other platforms.

## Lead
Abhishek & Ram

## No. of volunteers
- Per sponsors we need one volunteer.

## Troublemaker
- Ritesh

## ETA

- [ ] Content team needs to make announcements 

- [ ]  Expo needs to be prepared by Sunday 10:00 PM

**Comment by vipulgupta2048** [comment]
Update:
- We have included Job fair into PPG and will make the same content into a blog (Keeping it DRY)
- Later, Social Media and Job team can pick the same content and spam it everywhere else.
