### ISSUE TITLE
Minimal website deployment with dates and venue

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2020-tasks#2]

**Comment by ananyo2012** [comment]
Website live at https://in.pycon.org/2020/

**Comment by iambibhas** [comment]
Can we show the "Submit a proposal" button once the cfp is open? Right now it's the primary action button on the site but doesn't do anything.

**Comment by ananyo2012** [comment]
@iambibhas Ok I will make it disabled for now

**Comment by ananyo2012** [comment]
Updated
