### ISSUE TITLE
Design a basic template which we will use while posting announcements. 

### ISSUE THREAD

**Issue by rayandas** [pythonindia/inpycon2020-tasks#21]

**Comment by noblebatman** [comment]
Is anyone working on designing this one!?

**Comment by iamaravindsekar** [comment]
@rayandas is anyone working on this one!? If not please let me know. Will get it done!

**Comment by rayandas** [comment]
@noblebatman hey, sure go ahead. no one is working on this.

**Comment by iamaravindsekar** [comment]
Great... Thank you ✌🏼

**Comment by iamaravindsekar** [comment]
Before starting up with this, we have to discuss regarding the theme and design system we will be using this year. Once this is done we will be good to go ✌🏼

**Comment by ananyo2012** [comment]
The Design team is working on the Theme and logo. I will update once that
is done.

**Comment by SaptakS** [comment]
@rayandas @noblebatman @ananyo2012 we also need to decide on how we share the layout.
- canva (which would probably not need much expertise from social media team to use design tools)?
- Figma (which would need some expertise to use design tools, but nothing extra to download)
- Any specific tool?

@ananyo2012 @noblebatman any pointers on how it was done last year?

**Comment by ananyo2012** [comment]
I would recommend canva as it is easy to collaborate and no software
installation needed.

**Comment by iamaravindsekar** [comment]
I haven't used canva.. Regarding Figma, It has lots of features and also... it supports various file formats... Say I am using XD or Illustrator, I can directly copy an artboard to that or I can open the SVGs or Illustrator files on it... What I would suggest is we should consider an application that is flexible, user friendly and lightweight... Again.... if we are going to deal only with vectors, we can have Figma, XD, Illustrator,Canva (I havent used it )... but if we are going to edit the whole image itself, we need photoshop.... Before proceeding we need to have this in mind...

**Comment by iamaravindsekar** [comment]
@rayandas how do we classify these templates that we have to design for social media like speakers, promotion, sponsors,etc... Need more clarity on this...!!

**Comment by Pradhvan** [comment]
@noblebatman hey! Let me share a few of the templates that the team used last year so that it would help in clearing the confusion. 

Below I have attached two tweets that show the template, as you can see base template remained the same for both sponsor announcements and community announcements. 

[Community announcement poster-1](https://twitter.com/pyconindia/status/1171997502721146880)
[Sponsor announcement poster-2](https://twitter.com/pyconindia/status/1178539377586098176)

>@rayandas how do we classify these templates that we have to design for social media like speakers, promotion, sponsors,etc...

Regarding the classification, I guess it's primarily done on the basis of design and it's up to you how you go ahead with the designing the templates. Besides, other members from the design team would have feedback on those templates so the whole feedback iteration would help anyway. 😄 

Community/general announcements templates are the highest priority right now so you can work on that first. 

I hope this clears the confusion. 😄

**Comment by iamaravindsekar** [comment]
Yes yes understood... Thank you @Pradhvan 😊

**Comment by iamaravindsekar** [comment]
@Pradhvan @rayandas @ananyo2012 Done with some templates, Kindly let me know if there is anything else :)
This is the Figma url to the templates,
https://www.figma.com/file/l3fowoKJ1OAyXRd7j095r5/PyconIND-Assets?node-id=12%3A763

**Comment by sayanchowdhury** [comment]
Great work @noblebatman 

A couple of feedback from my side:
- Social media icons are not useful in templates.
- I personally like second and fourth. 
- Can we have the background of 4th in 1st? Maybe scaling down a few things to make adjustment for placeholder.

**Comment by noblebatman** [comment]
Thank you @sayanchowdhury, 
btw, Is this what you were telling about the first template!?

![image](https://user-images.githubusercontent.com/20441340/82484466-98d64400-9af7-11ea-8112-236e68d6739f.png)

**Comment by iamaravindsekar** [comment]
Thank you @sayanchowdhury ,
Btw.. Is this what you were asking to do with the first template in your third feedback?

![image](https://user-images.githubusercontent.com/20441340/82484827-1e59f400-9af8-11ea-8240-57cf2cd4aa10.png)

**Comment by sayanchowdhury** [comment]
> Btw.. Is this what you were asking to do with the first template in your third feedback?

I mean to use this background
![image](https://user-images.githubusercontent.com/500628/82726741-b37d0880-9d03-11ea-8f1e-c59e9162036e.png)

in this image
![image](https://user-images.githubusercontent.com/500628/82726745-c394e800-9d03-11ea-9a64-da6d3af42a18.png)

**Comment by ananyo2012** [comment]
@sayanchowdhury First one is a general announcement template with longer content while fourth is a speaker template with short content. Maybe you can mention which elements you like to have ?

**Comment by ananyo2012** [comment]
My comments
- Agree on removing the social media logos
- 1st, 2nd and 4th look good
- Adding to Sayan's comment, You can try using the logo as is on top and use the lanterns in the right with the 4th background

![logo](https://user-images.githubusercontent.com/10486343/82727819-6ea8a000-9d0a-11ea-86af-b61cc4cbcae5.PNG)

**Comment by iamaravindsekar** [comment]
@ananyo2012 Made a separate copy of templates with your inputs,Please feel free to check them. Btw, having the decorated Python symbol with the Pycon india logo is fine, but If its separate, it ll be visually appealing... and the logo can be broken down or put together as we wish, having the event title alone on the top will make things look more balanced.

**Comment by ananyo2012** [comment]
This is good to be closed
