### ISSUE TITLE
Have to announce from Twitter, LinkedIn and Facebook

### ISSUE THREAD

**Issue by rayandas** [pythonindia/inpycon2020-tasks#22]

**Comment by Pradhvan** [comment]
This is the draft for the initial announcement, we will be creating a thread for twitter and for rest of the platforms, it will be posted as a single post. 

```

Thread [1/3]
We are back with the 12th edition of PyCon India this time in Bangalore, the Garden City of India from 2 - 5 October. More details regarding CFP, tickets, and workshops coming soon. 

https://in.pycon.org/

Thread[2/3]

PyCon India is a volunteer-driven conference and we are looking out of volunteers who can help out in any way possible. So if you want to be part of the volunteering team do fill out the form. :smile: 

Form Link: https://forms.gle/tgxhNBMqwiPr2k1u6

Thread[3/3]

The communication platform for the conference is kept open and is the same as last year.  So feel free to interact with the community either in the Zulip chat or on Freenode network #pyconindia

Zulip Channel Link: https://pyconindia.zulipchat.com/#narrow/stream/224385-2020.2Fdiscussion
```

**Comment by palnabarun** [comment]
s/Banglore/Bangalore

**Comment by Pradhvan** [comment]
Twitter post link: https://twitter.com/pyconindia/status/1236960088390127616 

LinkedIn post link: https://www.linkedin.com/feed/update/urn:li:activity:6642728428372103168 

Facebook post link:
https://www.facebook.com/133849919970392/posts/3065938010094887/

**Comment by inovizz** [comment]
I think Facebook and Twitter DP needs to be of better quality. The current one is little pixelated.

Also, please update the image in zulipchat workspace. The thumbnail on zulipchat link shows image of previous year.

**Comment by ananyo2012** [comment]
Here is a high resolution image of the logo
![logo_lg_cropped](https://user-images.githubusercontent.com/10486343/76207137-3d4c2800-6223-11ea-87ef-3fd6d93cfe8a.png)

**Comment by ananyo2012** [comment]
> I think Facebook and Twitter DP needs to be of better quality. The current one is little pixelated.
> 
> Also, please update the image in zulipchat workspace. The thumbnail on zulipchat link shows image of previous year.

@inovizz Updated the details in Zulip

**Comment by rayandas** [comment]
> I think Facebook and Twitter DP needs to be of better quality. The current one is little pixelated.
> 
> Also, please update the image in zulipchat workspace. The thumbnail on zulipchat link shows image of previous year.

@inovizz Updated the high resolution image.

**Comment by rayandas** [comment]
Closing the issue.
