### ISSUE TITLE
Share keynote suggestion email from all social media channels. 

### ISSUE THREAD

**Issue by Pradhvan** [pythonindia/inpycon2020-tasks#23]
**Draft to be sent on Twitter:** 

PyCon India is a community first conference we want you to suggest who from the diverse Python community you would like to see as this year's keynote. We would do our best to make it possible.

To pass on your suggestion please reply to the email: https://mail.python.org/pipermail/inpycon/2020-March/013023.html

**Draft to be sent on Facebook and LinkedIn:** 

One of the things that makes a conference memorable are the keynotes. Since PyCon India is a community first conference, we want you to suggest who from the diverse Python community you would like to see as this year's keynote. We would do our best to make it possible.

To pass on your suggestion please reply to the email: https://mail.python.org/pipermail/inpycon/2020-March/013023.html

**Comment by championshuttler** [comment]
To pass on your suggestion ~just~ please reply to the email: https://mail.python.org/pipermail/inpycon/2020-March/013023.html

**Comment by rayandas** [comment]
Also attache the link for bottom post. On second thread.

**Comment by Pradhvan** [comment]
@rayandas bottom post ?

**Comment by rayandas** [comment]
@Pradhvan  mailing list etiquette. http://www.shakthimaan.com/downloads/glv/presentations/mailing-list-etiquette.pdf
Don't know if we should post it too or not.

**Comment by Pradhvan** [comment]
Email explicitly mentions not to do top-posting. So I guess it would be fine.

**Comment by sayanchowdhury** [comment]
> @Pradhvan mailing list etiquette. http://www.shakthimaan.com/downloads/glv/presentations/mailing-list-etiquette.pdf
> Don't know if we should post it too or not.

This is already there in the footer of the mailing list.

**Comment by Pradhvan** [comment]
Link to twitter post: https://twitter.com/pyconindia/status/1237610786303791104 

Link to LinkedIn post: https://www.linkedin.com/feed/update/urn:li:activity:6643376920778117120

Link to Facebook post: https://m.facebook.com/story.php?story_fbid=3070684499620238&id=133849919970392
