### ISSUE TITLE
Create a Volunteer Dependency Graph and link it to volunteer form

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2020-tasks#24]
Many people are not aware of roles/responsibilities of different teams. A dependency Graph with Roles/Responsibilities of each team will make it clear.

**Comment by ananyo2012** [comment]
First draft. Image attached below
![Volunteer-Dependency-Graph](https://user-images.githubusercontent.com/10486343/76348318-00208c80-632e-11ea-89e3-1f8886da8b69.png)

**Comment by ananyo2012** [comment]
@sayanchowdhury I haven't added the Diversity team yet which is mentioned in the volunteer form. Managing PyLadies Conference and CoC will be primary responsibilities right ?

**Comment by bravegnu** [comment]
* Encouraging women to participate, especially wrt to talk submission.
     - Blog articles
     - Social media promotion
  * Manning the PyLadies booth, if any.
  * Arrange PyLadies Lunch.
  * Arrange Child Care.

You can check with @sharmi who lead the effort last year.

**Comment by ananyo2012** [comment]
Thanks @bravegnu I have updated few of the points in the image. We are yet to decide on the PyLadies Lunch which Anwesha will be leading efforts. Here is the updated image

![Volunteer-Dependency-Graph](https://user-images.githubusercontent.com/10486343/76487333-1e7aab00-6448-11ea-86fd-821e7ddbda5b.png)

**Comment by ananyo2012** [comment]
@sayanchowdhury I am adding this image in volunteer form description.

**Comment by sayanchowdhury** [comment]
Given we are planning to have the WG rolling, can we migrate this doc to the handbook?
