### ISSUE TITLE
Update social media channels about the delay in CFP

### ISSUE THREAD

**Issue by Pradhvan** [pythonindia/inpycon2020-tasks#26]
**Draft to posted:** 

Due to the COVID-19 pandemic, we have decided to delay the Call For Papers (CFP) that was supposed to go live today. The conference is scheduled in October as of now and an update regarding CFP will be posted by next week.

**Comment by sayanchowdhury** [comment]
Looks good to me.

**Comment by anistark** [comment]
LGTM

**Comment by Pradhvan** [comment]
Link to tweet: https://twitter.com/pyconindia/status/1238148263745687552
