### ISSUE TITLE
Gather a list of people to be in the review panel

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2020-tasks#31]
Get a list of suggestion from the team who would be in the review panel. This also overlaps with the work of the mentorship panel as we can reach out to the review panel for mentorship

**Comment by raukadah** [comment]
We have started receiving replies from previous years speakers for mentoring and reviewing. I will put up the list and draft a reply for them.

**Comment by sayanchowdhury** [comment]
Duplicate of #32
