### ISSUE TITLE
Make website component designs

### ISSUE THREAD

**Issue by SaptakS** [pythonindia/inpycon2020-tasks#34]
Based on the different logo options receiving maximum votes, we will start making design components for the website:

- [x] Heading banner section with navigation (In progress)
- [x] About section - Describing decision to go online (in progress)
- [x] Speakers section (in progress)
- [ ] Schedule section
- [x] Blog index page (in progress)
- [x] Single blog post
- [x] Ticket and registration section

The main goals are to make websites:
* Informative
* Give the feel of Online
* Responsive and Inclusive

**Comment by SaptakS** [comment]
The following were the design ideas proposed:
Design 1:
![Guru-Design](https://user-images.githubusercontent.com/9530293/81825362-30fe8700-9554-11ea-898c-4b3f23188ab1.png)

Design 2:
![Sid-Design](https://user-images.githubusercontent.com/9530293/81826131-14af1a00-9555-11ea-9c30-5d31f77cdba7.png)

We are planning to stick with Design 1. Reasons:

1. Design 2 looks a little empty
2. The logo doesn't really go as banner
3. Design 1 has a nice mix of Indian Vibe and Tech Vibe (though we are planning to increase the tech vibe a notch)
4. I personally like Design 1 :P

**Comment by ananyo2012** [comment]
This is the finalized design

![website-mockup](https://user-images.githubusercontent.com/10486343/83296884-265c1700-a20f-11ea-98e7-cc6a79124719.PNG)
