### ISSUE TITLE
E2E Networks dashboard access

### ISSUE THREAD

**Issue by palnabarun** [pythonindia/inpycon2020-tasks#37]
Taking backups of the `in.pycon.org` VM would require access to the dashboard of E2E networks account owning the VM

**Comment by sayanchowdhury** [comment]
We tried contacting everyone we know the community to know who has the details E2E networks but no one knows. I will drop the email today to the mailing asking who has access to the servers.


On the other hand, we also contacted the E2E Networks team, but we have not got any positive response from them. I will drop another reminder email to reply to the ticket today.

**Comment by ananyo2012** [comment]
Did you try contacting Amit Singh Sethi ? He used to work at E2E. You can
mail him and see if he still works there.

**Comment by palnabarun** [comment]
Updates
---
1. I had a call with Vignesh. He gave me the access to E2E networks dashboard.
2. He also mentioned that he has access to the `python.org.in` and `pythonexpress.org` and will share the details after we set up the credential storage.
