### ISSUE TITLE
Divide organizing team amongst CFP topics

### ISSUE THREAD

**Issue by palnabarun** [pythonindia/inpycon2020-tasks#39]
They will be gatekeepers for all CFP reviews and monitor the CFP review process.

This would help in removing discrepancies and prevent further scrutiny.

- Decentralised and Distributed Technology (Blockchain, Tangle or any DLT protocol or infrastructure related product) 
- Desktop Applications (Qt, GTK+, Tkinter, Gnome, KDE, Accessibility)
- Scientific Computing (Python usage in scientific computing and research. GIS, Mathematics, Simulations)
- Game Design and 3D Modelling (Python in developing games, 3-D modelling and animation)
- Culture and society (Diversity, health, productivity, workspace issues, privacy, community building, coding for causes)
- Embedded Python and IOT (MicroPython, Python on Hardware, Robotics, Arduino and Raspberry Pi)
- Networking and Security (Network Programming, Network Security and Encryption)
- Web development (Web, Apis, Microservices)
- Developer tools and automation (Testing, CI/CD, Containers, Orchestration, Logging and Monitoring)
- Data Science, Machine Learning and AI
- Core Python (Language Features, Python Implementations, Extending Python and Standard Library, language internals)

**Comment by anistark** [comment]
Can't seem to assign Ritesh here.
Will ping him on Zulip.

**Comment by sayanchowdhury** [comment]
Ritesh isn't on the team yet. I've sent the invitation. We can assign once he accepts

**Comment by RiteshAgrawal** [comment]
@sayanchowdhury In this, do you mean select people responsible for each of the topic?

**Comment by sayanchowdhury** [comment]
This is primarily the review process, there would be someone from the organizing team, as in the core people, who would keep a close eye on the work of the volunteer and see the rules are followed properly

**Comment by sayanchowdhury** [comment]
@RiteshAgrawal Did we do any update on this one?
