### ISSUE TITLE
Fetch out the previous year's PyCon India 2020 speakers

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2020-tasks#40]
In order to get good list of tasks, We need to reach out to people for that. Pulling the email of previous years speakers and emailing them will help us to get better speakers.

**Comment by palnabarun** [comment]
Tasks
---
- [x] Fetch the previous year speakers email ID
- [x] Provide the data to Anirudha and Chandan
- [x] Anirudha and Chandan to email them

**Comment by sayanchowdhury** [comment]
Did we send the email over the weekend?

**Comment by raukadah** [comment]
Emails are sent out to all the previous year speakers. Marking this as done
