### ISSUE TITLE
[RFC] Website + Blog Migration to Netlify

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2020-tasks#42]
We want to move to Netlify for the static websites + blog and move away from the present PyCon India Server.
**Advantages**
- Lesser things to manage from the server
- More seamless deployment flow using CI/CD
- Remove confusion with deployment from magudi for website/blog which had more frequent changes than junction
- More visibility on deployment setup

**Disadvantages**
- Dependence on the deployment platform which may change in future
- Additional cost involved with deployment

**Requirements**
- Access to PyCon India Domain provider account used to register `pycon.afrost.org` which is currently linked to `in.pycon.org`
- Select an appropriate static Deployment platform. Netlify is the preferred choice
- Select an appropriate CI platform - GitHub Actions/Travis CI
- Move to git sub-modules architecture for blog and website
- Come with a documentation for the Deployment Architecture

**Comment by astronomersiva** [comment]
@ananyo2012, I hope you have factored in the cost of Netlify as well. The free plan only allows 300 build minutes per month.

**Comment by ananyo2012** [comment]
@astronomersiva Added it to the list of Disadvantages. We can calculate the costs involved and decide. There maybe ways to build in CI and push the dist to Netlify. Need to explore on that.

**Comment by palnabarun** [comment]
> We want to move to Netlify for the static websites + blog and move away from the present PyCon India Server.

We did not decide on moving it bdw, it's just an experiment.

> Lesser things to manage from the server

We would still need to have rewrite rules on nginx.

> Remove confusion with deployment from magudi for website/blog which had more frequent changes than junction

I don't remember any discussion regarding "confusion with deployment"

> Access to PyCon India Domain provider account used to register pycon.afrost.org which is currently linked to in.pycon.org

Can you please elaborate a bit on the point?

> Move to git sub-modules architecture for blog and website

This is unrelated and independent issue bdw.

**Comment by ananyo2012** [comment]
> > We want to move to Netlify for the static websites + blog and move away from the present PyCon India Server.
> 
> We did not decide on moving it bdw, it's just an experiment.
> 
Thought to start the discussion related to that
> > Lesser things to manage from the server
> 
> We would still need to have rewrite rules on nginx.
> 
Are you intending to deploy on Netlify and have redirect rules on server to point to the blog ?
> > Remove confusion with deployment from magudi for website/blog which had more frequent changes than junction
> 
> I don't remember any discussion regarding "confusion with deployment"
> 
I added this point to account for the present dependence of deployment of website over magudi. There is no CD happening and everytime it needs to be manually deployed.
> > Access to PyCon India Domain provider account used to register pycon.afrost.org which is currently linked to in.pycon.org
> 
> Can you please elaborate a bit on the point?
> 
As per my understanding moving to a new deployment platform meant CNAMing it to the domain provider, but as per your 2nd comment you want to do it via redirect rules if I understood correctly ?
> > Move to git sub-modules architecture for blog and website
> 
> This is unrelated and independent issue bdw.

Website and blog are similar thing and I think if we are planning to use submodules then we can integrate both together.

**Comment by anistark** [comment]
> > > Lesser things to manage from the server
> > 
> > 
> > We would still need to have rewrite rules on nginx.
> 
> Are you intending to deploy on Netlify and have redirect rules on server to point to the blog ?

I don't think we need to write any rules on nginx. It's a static site. Can directly connect to netlify host via CNAME. Same goes for blog I believe.
For junction, we'd still need server though.

**Comment by palnabarun** [comment]
> I don't think we need to write any rules on nginx. It's a static site. Can directly connect to netlify host via CNAME. Same goes for blog I believe. For junction, we'd still need server though.

How do you CNAME `https://in.pycon.org/blog` to `https://project-url.netlify.app`?

cc: @ananyo2012 @anistark

**Comment by ananyo2012** [comment]
@palnabarun You just need to build the project in a `blog` directory under the `output` folder. Then everything will be visible under `/blog` domain.

**Comment by palnabarun** [comment]
@ananyo2012 Well, you are thinking only about the blog here and not other components. Think it through once considering everything that we deploy under that subdomain.

**Comment by ananyo2012** [comment]
Well we don't intend to move everything under the subdomains to Netlify.
Just the static components.

**Comment by palnabarun** [comment]
Exactly! That's what I have been trying to say along.

How would you CNAME then?

**Comment by ananyo2012** [comment]
So my idea was to deploy the static components in Netlify that would be
Website and blog keep them under subfolder setup. Then CNAME the netlify
domain to the PyCon India domain.

Keep the CFP website in the server under `/cfp` url which is CNAMEd to
PyCon India domain as well.

Is this setup possible ?

**Comment by ananyo2012** [comment]
I just searched regarding this and found we can't have multiple CNAMEs for
a domain. Ref:
https://serverfault.com/questions/574072/can-we-have-multiple-cnames-for-a-single-name

**Comment by palnabarun** [comment]
> I just searched regarding this and found we can't have multiple CNAMEs for a domain.

I would have Google'd it for you, otherwise. :)

**Comment by ananyo2012** [comment]
My next question is redirect to a different domain have any drawbacks ?
