### ISSUE TITLE
Cross-post on all Community Mailing Lists

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2020-tasks#44]
We need to increase our proposals. One way is to post on other relevant streams, including other community mailing lists, slack/discord/telegram channels.
Please add any relevant community list that resonates with the same:

- [x] [BangPypers](https://mail.python.org/mailman/listinfo/bangpypers)
- [x] PythonPune
- [x] [HydPy](https://mail.python.org/mailman3/lists/hydpy.python.org/)
- [x] ChennaiPy
- [x] [PyDelhi Mailing list](https://bit.ly/pydelhi-mailinglist)
- [x] [PSF-Community](https://mail.python.org/mailman/listinfo/psf-community)

**Comment by vipulgupta2048** [comment]
Updated PyDelhi mailing list.

**Comment by pshirali** [comment]
@anistark . I'm on a Slack group called Python Developers (pythondev.slack.com). I can post there.

May I recommend that the organisers setup the following:

1. A standard core-message that could be posted across all media. This will help ensure that the core information (dates, info) is correct, and remains consistent. People could prefix and suffix this core message and make it theirs.
2. One or more hashtags that we can commonly agree to use across all media

**Comment by anistark** [comment]
@pshirali Please do post. Can use as much help as we can get.

As for messaging:

```
Hi all,

PyCon India 2020 is live and calling all the brilliant pythonistas to submit their proposals for talk. PyCon India 2020 will be held on October 2nd and 3rd, completely online. So, no matter where you're at, you'll be able to join in the action.

View other proposals and submit yours: https://in.pycon.org/cfp/2020/proposals/
Read more about our CFP guidelines: https://in.pycon.org/blog/2020/2020-call-for-proposals-announcement.html
```

**Comment by pshirali** [comment]
@anistark Done. This is on `#conferences` of PySlackers (pythondev.slack.com). I'll keep a look out for more avenues. Thanks for sharing the text. :)

![pydev](https://user-images.githubusercontent.com/39181224/83339177-d05ba200-a2e8-11ea-8bfd-032c295d7711.png)

**Comment by sayanchowdhury** [comment]
I updated the PSF-Community mailing list in the list.

We already have a wiki page listing all the Python meetup groups in the handbook, can update the wiki page along with slack channels, mailing list etc?

We also have this [list](https://wiki.python.org/moin/LocalUserGroups#India)

**Comment by anistark** [comment]
We've posted and re-posted this. Closing the issue from here. Progress taken over by cfp volunteers.
