### ISSUE TITLE
Collect all Keynote Speaker suggestions from Social Media

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2020-tasks#46]
TSIA

**Comment by ananyo2012** [comment]
Done: https://github.com/pythonindia/inpycon2020-tasks/wiki/Keynote-Speaker-Suggestions

**Comment by Pradhvan** [comment]
@ananyo2012 We should remove names that have been a keynote speaker in the past years. Of what I know we don't usually have a repeated keynote speaker. So we should remove names from the list that way we don't end up connecting to them again for the keynote.

**Comment by inovizz** [comment]
I think Dave Beazley has keynoted PyCon India twice 😉

**Comment by Pradhvan** [comment]
@inovizz sadly no, but I would want to hear him in the near future. 😄

**Comment by inovizz** [comment]
Oops, my bad. It was always in my head that Dave Beazley keynoted 2011 version of PyCon India. However, I just checked it was Raymond Hettinger. I think I got confused between two legends 😉.

**Comment by ananyo2012** [comment]
Yes I just collected everything we got. Now we need to select the names we
want to send emails

**Comment by satyaakam** [comment]
Can you send the list or the link to the list to the mailing list as well
