### ISSUE TITLE
Select Keynote Speakers to send email

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2020-tasks#47]
Select Keynote Speakers from this list - https://github.com/pythonindia/inpycon2020-tasks/wiki/Keynote-Speaker-Suggestions

**Comment by satyaakam** [comment]
I did see one mail in March asking for suggestions on mailing list  i think we should ask again

**Comment by KanakKvdi** [comment]
Greetings! I want to contribute by adding a keynote speaker suggestion in the wiki, as well as email them. How can I proceed?

**Comment by anistark** [comment]
@KanakKvdi Add your suggestions here itself. Someone will add it to the list.

**Comment by KanakKvdi** [comment]
Greetings of the day!

My suggestion:

*Dr. Chuck* from The University of Michigan

His Twitter: *@drchuck*

Please let me know how I can help further.

Best Regards*,*

Kanak Kavadi

**Comment by sayanchowdhury** [comment]
We've shortlisted from the community-recommended keynote speaker list. Marking this issue resolved :heavy_check_mark: 

Thank you everyone who participated.
