### ISSUE TITLE
Logo design which one we are going with ?

### ISSUE THREAD

**Issue by satyaakam** [pythonindia/inpycon2020-tasks#48]
i see two variants of logo one on the website and one on the twitter handle which one are we going with ?
![Screenshot 2020-06-09 at 5 26 58 PM](https://user-images.githubusercontent.com/822770/84144821-87d57e80-aa76-11ea-83fc-48f077745d85.png)
![Screenshot 2020-06-09 at 5 27 11 PM](https://user-images.githubusercontent.com/822770/84144838-8ad06f00-aa76-11ea-9d4e-54ee17c3f859.png)

**Comment by SaptakS** [comment]
We are going with the yellow and red one. The website is being currently updated to follow the new logo, theme and designs. The code can be found in the dev branch of inpycon2020 repo. Expecting to deploy the new website end of this week.

**Comment by satyaakam** [comment]
ok do we have some brand guidelines listed somewhere

**Comment by SaptakS** [comment]
As far as I know, not yet. @sayanchowdhury correct me if I am wrong. We are going to maintain a [git repo](https://github.com/pythonindia/inpycon-assets) with all the branding images and assets.

**Comment by KanakKvdi** [comment]
This new logo looks great though.

**Comment by anistark** [comment]
We can close this now? 
@satyaakam @SaptakS

**Comment by satyaakam** [comment]
Yes Good to close this
