### ISSUE TITLE
Zulip does not work 

### ISSUE THREAD

**Issue by satyaakam** [pythonindia/inpycon2020-tasks#49]
Zulip sucks and has not worked in past as well for communications , put me onto all the Telegram or Whatsapp groups for communications with working groups

**Comment by anistark** [comment]
@satyaakam What problems did you face with Zulip?

**Comment by satyaakam** [comment]
i always get lost in the lost for simple things like how to reply because of interface , which Whatsapp and Telegram makes things easy and getting things done
