### ISSUE TITLE
Need to update the mailing list information

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon2020-tasks#50]
Checked out --> https://mail.python.org/mailman/listinfo/inpycon
Need to update the information here. 

We are writing the volunteer blog for it as well. cc: @rithin-jose @Sc0rpi0n101

**Comment by Sc0rpi0n101** [comment]
Other than updating the link for volunteers, Is there anything else that should be updated in the content?

**Comment by sayanchowdhury** [comment]
This is fixed.
