### ISSUE TITLE
Create editorial about Workshop

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2020-tasks#53]
We need to update the CFP editorial to include a section about Workshop and the format we are going to follow for the Workshops

**Comment by anistark** [comment]
@vipulgupta2048 Can you put together a write-up for this?

**Comment by ananyo2012** [comment]
@vipulgupta2048 Can you prioritize this task ?

**Comment by vipulgupta2048** [comment]
LOL. I wrote the post but didn't make the PR. Coming up in 10 minutes. I think I wanted to re-read what I wrote with a fresh mind.

**Comment by anistark** [comment]
@vipulgupta2048 Let's push this today ?

**Comment by vipulgupta2048** [comment]
@anistark Pushed the changes requested during the call that day, waiting for @ananyo2012's review or if you can check it out.
https://github.com/pythonindia/inpycon-blog/pull/285

**Comment by ananyo2012** [comment]
I just commented on the PR for some changes. @anistark @vipulgupta2048 Please have a look.

**Comment by ananyo2012** [comment]
Also created the content for the CFP page at https://pad.riseup.net/p/inpycon-2020-workshop-editorial

**Comment by sayanchowdhury** [comment]
What is the status on this? @anistark @vipulgupta2048

**Comment by anistark** [comment]
This has been done.
