### ISSUE TITLE
Create an announcment about Workshops

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2020-tasks#54]
We need to send an announcment to social media for Workshop proposal announcement

**Comment by ananyo2012** [comment]
Do this once #53 is done

**Comment by Pradhvan** [comment]
@ananyo2012 this is for the CFP announcement of Workshops ?

**Comment by Pradhvan** [comment]
We can use this poster? Waiting for @vipulgupta2048 to finish up the write-up than will do an announcement on all social media channels. 😄 


![Announcement templete1(2)](https://user-images.githubusercontent.com/13925830/85290030-f3c3d800-b4b5-11ea-8baa-9c38fb842b32.png)

**Comment by Pradhvan** [comment]
Post for announcement  
```
CFP for PyCon India workshops is open 💯

Workshops @ PyCon India are awesome deep dives into complex concepts with a practical hands-on approach. Here's our team sharing some great insights about giving a great workshop at PyCon India.
<blog link below>
<Poster added here>
```

**Comment by vipulgupta2048** [comment]
So actually the post has been changed into writing a great workshop proposal. So we might need to tweak the tweet a bit. 

CFP for PyCon India workshops is now open 💯

Workshops at PyCon India have been awesome deep dives into complex concepts with a practical hands-on approach. Here's our team sharing insights about how you too can write a great workshop proposal.

How does that sound?

**Comment by Pradhvan** [comment]
LGTM 😄

**Comment by Pradhvan** [comment]
Announcement is done, [tweet](https://twitter.com/pyconindia/status/1277211351820021761) . Thank you for the help @vipulgupta2048 @ananyo2012 @anistark 😀
