### ISSUE TITLE
Add Video best practices on Editorial page

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon2020-tasks#55]
I feel it would be immensely helpful if the best practices to create a video is available right on the editorial page -https://in.pycon.org/cfp/2020/proposals/ since most proposal submitters don't give much attention to the blogs. Rather just go on to submit, after reading the editorial page. 

We can take the content from - https://in.pycon.org/blog/2020/2020-call-for-proposals-announcement.html
And, also update the content present on the page.

**Comment by vipulgupta2048** [comment]
Sounds good. It just needs a simple copy and paste to be honest.

**Comment by sayanchowdhury** [comment]
What this issue resolved?

**Comment by anistark** [comment]
Slipped off. Marking as done.
