### ISSUE TITLE
Need content pieces for Outreach Partners

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2020-tasks#56]
Since last call, we can onboard outreach partners to help us spread the word about PyCon India 2020, we would a few content pieces as mentioned below to send out to them:

- [ ] **Official Invitation to be Outreach Partners**: This will include an overview about PyCon India, who we are, how we do things and so on. What's required of them and we would be offering them. Ideally, they would need to send mails and post on their community social channels about PyCon India. We would be putting up their logo on PyCon India website under _Outreach Partners_.

- [ ] **Mail content** for our outreach partners to send out in their mailing lists.

- [ ] **Social post content**: Tweet and Facebook post and other short social post types content.

**Comment by anistark** [comment]
@vipulgupta2048 Can we get an update on this? Is someone available to take this up?

**Comment by vipulgupta2048** [comment]
@anistark Let me post again if someone wants to take this up otherwise I and @sc0rpi0n101 can take care of this

**Comment by Madhura12gj** [comment]
> @anistark Let me post again if someone wants to take this up otherwise I and @Sc0rpi0n101 can take care of this

Hey Vipul, let me know where can I help in this.

**Comment by vipulgupta2048** [comment]
Thanks, @Madhura12gj for taking this up, 
This time around we are looking for Outreach Partners or much simpler other communities who can help us get the word out regarding PyCon India as @anistark mentioned in the issue. At the moment, we need content for an invite that can be sent to communities to become an outreach partner for PyCon India 2020. We need to mention what all it would entail + we can put the communities's logo on our PyCon India website that would be helping both parties involved. Let me know if you need any more information @anistark can help you out. Reaching us on Zulip would be faster.

**Comment by anistark** [comment]
Here's more info: https://github.com/pythonindia/inpycon2020-tasks/wiki/Outreach-Partners

**Comment by Sc0rpi0n101** [comment]
Looks like @Madhura12gj is a little busy atm 
I'll work on this.

**Comment by Sc0rpi0n101** [comment]
For reference, 

The PR for the Outreach partners blog is https://github.com/pythonindia/inpycon-blog/pull/289
and for the Outreach partners email is https://github.com/pythonindia/pyconindia-handbook/pull/31

**Comment by sayanchowdhury** [comment]
This also has been done. Marking as resolved :heavy_check_mark:
