### ISSUE TITLE
Create Website Ticket Section Design

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2020-tasks#57]

**Comment by ananyo2012** [comment]
First version at https://www.figma.com/file/l3fowoKJ1OAyXRd7j095r5/PyconIND-Assets?node-id=439%3A1

**Comment by sayanchowdhury** [comment]
The frontend has been done. We would need to integrate it with Townscript.

**Comment by sayanchowdhury** [comment]
The tickets are pushed and live. We can close this issue now.

Thanks for everyone involved.
