### ISSUE TITLE
Create team to manage Junction and Infra team

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2020-tasks#6]
Once created, comment on this ticket the members of the group.

**Comment by pradyunsg** [comment]
Flagging that it might be handy to list this team in the README.

**Comment by palnabarun** [comment]
This team is ephemeral and many people might not continue beyond PyCon India 2020. We can always use the reference to the GitHub Team.

**Comment by palnabarun** [comment]
Thte requisite GH teams had been created long back.
