### ISSUE TITLE
Need a blog post on mentorship.

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2020-tasks#61]
Some Notes:

- If anybody is needs help to look at their cfp before submitting.
- Refer to good cfp writing practice.
- They can join zulip or via emails/calls ask us specific questions that they are stuck with.

**Comment by vipulgupta2048** [comment]
Assigning @Anpr1211 for this blog post, please do ask your questions.

**Comment by Anpr1211** [comment]
Reiterating the questions by @vipulgupta2048 on Zulip:
1. How does one get help from mentors, do we have a process in place?
2. Calls? Do we provide calling to ask questions on things folks are stuck on?
3. Do we have some sample talk proposals that can be used as examples?

**Comment by vipulgupta2048** [comment]
@siddharthvipul @abhishekmishragithub can you folks help out @Anpr1211, thanks! We are lookin' to complete the first draft by the weekend, if you can share the documented process with Ankita, that would be great.

**Comment by siddharthvipul** [comment]
> Reiterating the questions by @vipulgupta2048 on Zulip:
> 
>     1. How does one get help from mentors, do we have a process in place?
If need any help with CFP, please join [pycon India zulip](https://pyconindia.zulipchat.com/#) and drop a message in [pre-cfp topic of mentorship stream](https://pyconindia.zulipchat.com/#narrow/stream/245487-wg.2Fmentorship/topic/pre-cfp). You should get a response from the team and you will be asked to share a doc with comment access to a mentor (in a private message) who will help you polish the draft. If you don't get any response in 48 hours, please send a direct message to `@siddharthvipul`.
If text-based communication is not working for you, we also have a [call scheduled every Saturday 1500 IST to 1700 IST](https://meet.google.com/pot-jzjq-udn) where we will try to help you with the draft.

> 
>     2. Calls? Do we provide calling to ask questions on things folks are stuck on?
Yes but it's not on-demand or 1:1. It's a scheduled call open for all.
 
>     3. Do we have some sample talk proposals that can be used as examples?
@abhishekmishragithub I remember you mentioning that there are some materials. Can you please share them

**Comment by siddharthvipul** [comment]
@Anpr1211 
Let me know if you have any questions
Thank you for doing it, appreciate it!

**Comment by abhishekmishragithub** [comment]
> > Reiterating the questions by @vipulgupta2048 on Zulip:
> > ```
> > 1. How does one get help from mentors, do we have a process in place?
> > ```
> 
> If need any help with CFP, please join [pycon India zulip](https://pyconindia.zulipchat.com/#) and drop a message in [pre-cfp topic of mentorship stream](https://pyconindia.zulipchat.com/#narrow/stream/245487-wg.2Fmentorship/topic/pre-cfp). You should get a response from the team and you will be asked to share a doc with comment access to a mentor (in a private message) who will help you polish the draft. If you don't get any response in 48 hours, please send a direct message to `@siddharthvipul`.
> If text-based communication is not working for you, we also have a [call scheduled every Saturday 1500 IST to 1700 IST](https://meet.google.com/pot-jzjq-udn) where we will try to help you with the draft.
> 
> > ```
> > 2. Calls? Do we provide calling to ask questions on things folks are stuck on?
> > ```
> 
> Yes but it's not on-demand or 1:1. It's a scheduled call open for all.
> 
> > ```
> > 3. Do we have some sample talk proposals that can be used as examples?
> > ```
> 
> @abhishekmishragithub I remember you mentioning that there are some materials. Can you please share them

@Anpr1211 you can take reference from this or directly mention this blog URL: https://in.pycon.org/blog/2020/2020-workshop-cfp-announcement.html

Thanks @Anpr1211, let us know if anything else is needed :)

**Comment by vipulgupta2048** [comment]
Thanks folks @siddharthvipul @abhishekmishragithub @anistark for all the information. 
@Anpr1211 I think this will be enough for writing the blog post, do post any queries if you have.

**Comment by sayanchowdhury** [comment]
The blog post is pushed: https://in.pycon.org/blog/2020/announce-pycon-india-mentorship.htm

Closing the issue.
