### ISSUE TITLE
[High Priority] Create a FAQ for PyCon India 2020

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2020-tasks#67]
We need to set up a FAQ for PyCon India 2020. This can be incrementally changed. For now, we can pick up the relevant questions from last years, and add new to fit the online use case.

WGs comment the questions on this ticket which you think makes sense to add to the FAQ page.

/cc
@palnabarun 
@vipulgupta2048 
@anistark 
@RiteshAgrawal 
@raukadah 
@abhishekmishragithub 
@Pradhvan 
@rayandas 
@inovizz 
@vipulgupta2048

**Comment by Sc0rpi0n101** [comment]
I can create a draft for this with a few initial questions and post the docs link here tomorrow, and we can work on that. 
But yeah, please post the questions you would like us to answer in the FAQ.

**Comment by inovizz** [comment]
These two can be good starting references to compile the list of questions -

https://in.pycon.org/2018/faq.html

https://in.pycon.org/2019/faq.html

**Comment by palnabarun** [comment]
From what I wrote in the chat group:
```
Q. Do volunteers get a certificate?
Q. Do attendees get a certificate of participation?
Q. What does a contributor ticket mean?
Q. Do I, as a speaker, need to buy a ticket?
Q. Can I transfer my ticket(s)?
Q. Can I get a refund?
Q. Is there a student discount?
```

**Comment by sayanchowdhury** [comment]
@Sc0rpi0n101 I've assigned the work to you. You can directly create a PR and we can discuss it there.

**Comment by Sc0rpi0n101** [comment]
I've created a PR for the FAQ page - https://github.com/pythonindia/inpycon2020/pull/62

**Comment by Sc0rpi0n101** [comment]
Done in pythonindia/inpycon2020#62. Can be closed.

**Comment by sayanchowdhury** [comment]
Thanks @Sc0rpi0n101 for the PR, and everyone others involved.
