### ISSUE TITLE
Create the Sponsorship page and go live with announcements 

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2020-tasks#68]
Migrate pythonindia/inpycon2020#66 into the tasks repo

The sponsorship prospectus is live here: https://in.pycon.org/2020/sponsorship-prospectus.pdf
We have a section in the same PyCon India 2020 page to highlight this doc. We might use the previous year 
https://in.pycon.org/2019/#sponsorship contents for the website.

Apart from that, we need the following things to go live with announcements:

- [x] Blog content for Sponsorship

- [x] Email contents for announcements to various mailing lists

- [x] Social Media buzz

We will try to go live by the end of today.

**Comment by vipulgupta2048** [comment]
@Sc0rpi0n101  Will take up the blog

**Comment by raukadah** [comment]
May be getting a page something like this https://in.pycon.org/2019/sponsorship-prospectus.html will help to share on social media?

**Comment by sayanchowdhury** [comment]
Given the content is mostly same, we can pick the same content with the needed modifications.

**Comment by sayanchowdhury** [comment]
All the objectives are completed, hence closing this issue
