### ISSUE TITLE
Fix the issues in the Ticket blog and FAQ page

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2020-tasks#69]
There is inconsistency with the data that we have put in the Ticket blog and the FAQ page. The dev sprint ticket is free for all, irrespective of the people have the conference ticket or not.

**Comment by sayanchowdhury** [comment]
@Sc0rpi0n101 @vipulgupta2048 This is fixed, right?

**Comment by vipulgupta2048** [comment]
Yes, closing.
