### ISSUE TITLE
Clarify the role of Magudi with Vignesh

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2020-tasks#7]
Get status of Magudi, and given Vignesh has move out of the country. It would be great we have a second set of eyes looking into the infra problems.

**Comment by ananyo2012** [comment]
@palnabarun Shall we schedule a call on Thursday evening on this if Vignesh is available ?

**Comment by palnabarun** [comment]
@ananyo2012 Sure.

**Comment by palnabarun** [comment]
There was no response from Vignesh despite emails.

Figured out the workflow and simplified it by myself.
