### ISSUE TITLE
Ticket sales strategies. 

### ISSUE THREAD

**Issue by rayandas** [pythonindia/inpycon2020-tasks#72]
Points to keep in mind and apply:

- [ ] Post in LinkedIn groups (around 4AM - 5AM).

- [ ] Creative posters.

- [ ] Talk to/make campus ambassadors. 

- [ ] Reach out to companies.

- [ ] Show them we have job board.

**Comment by rayandas** [comment]
Please add more suggestions. I might have missed few points. 
cc: @inovizz @sayanchowdhury @palnabarun @anistark @RiteshAgrawal @Pradhvan @abhishekmishragithub

**Comment by sayanchowdhury** [comment]
@rayandas It would bee good to post the action items that the team decided in the last few meetings.

**Comment by rayandas** [comment]
**MOM for 6th September:**

Posts for 7 Sep - 12 Sep 

Tickets Post = 3 
Schedule Announcements: 1 

Tips: 

- Can we change the design for posters ? 
- More engagement tweets ?
- AMA for Local Python Meetup Communities ?
- AMA from the official PyCon India handle ? 
- Contact local communities social media managers 
- Memes for engagements ? 
- Badges for PyCon India ? 
- Share your swags tweets ? 
- PyCon India t-shirts ? 
- Can we get a give away of a ticket ? 
- Generating art with Python Post
- When is the closing of the ticket ?

**Comment by Pradhvan** [comment]
Closing this as regular tickets are sold out. 

Thank you everyone for helping in closing the issue.
