### ISSUE TITLE
Announce EPAM as GOLD SPONSOR

### ISSUE THREAD

**Issue by inovizz** [pythonindia/inpycon2020-tasks#87]
Scheduled: 19th Sep

Sponsor Name: EPAM India

Sponsor Tier: Gold

Sponsor Website: https://welcome.epam.in/
 
Sponsor Description:
Since 1993, EPAM Systems, Inc. (NYSE: EPAM) has leveraged its software engineering expertise to become a leading global product development, digital platform engineering, and top digital and product design agency. Through its ‘Engineering DNA’ and innovative strategy, consulting, and design capabilities, EPAM works in collaboration with its customers to deliver next-gen solutions that turn complex business challenges into real business outcomes. EPAM’s global teams serve customers in more than 30 countries across North America, Europe, Asia and Australia. As a recognized market leader in multiple categories among top global independent research agencies, EPAM was one of only four technology companies to appear on Forbes 25 Fastest Growing Public Tech Companies list every year of publication since 2013 and was the only IT services company featured on Fortune’s 100 Fastest-Growing Companies list of 2019.

Sponsor Logo: 
![EPAM_LOGO_Full_Color_RGB_Final](https://user-images.githubusercontent.com/3849885/93663821-126f4600-fa88-11ea-982a-2d3feaba4843.png)

## Tasks
- [x] Social Media announcement @Pradhvan 
- [x] Blog post announcement @vipulgupta2048 
- [x] Website update to display sponsor logo  @palnabarun 

### Pre 4PM
- [x] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @Pradhvan 
- [x] Merge the website changes @palnabarun

### Post 5PM
- [x] Deploy the blog and the website @palnabarun 
- [x] Send the social media announcements out @Pradhvan

**Comment by iamaravindsekar** [comment]
The announcement media can be found in this url, Thank You :)
[https://drive.google.com/file/d/1pDiFxG9uuFR6YstDClAHOA9Wr5JAvLMb/view?usp=sharing](url)

**Comment by inovizz** [comment]
Can you increase the height of the rectangle a little? @noblebatman

**Comment by iamaravindsekar** [comment]
Sure @inovizz, check this out.. 
![EpamPoster](https://user-images.githubusercontent.com/20441340/93664337-b5758f00-fa8b-11ea-80b2-d40a26690ccf.png)
now there is some optimal space white space at the top and bottom, updated the image in drive as well

**Comment by inovizz** [comment]
looks good.

**Comment by Sc0rpi0n101** [comment]
@inovizz do you have a link to the sponsor image or do I have to add it to the assets and then link that?

**Comment by Sc0rpi0n101** [comment]
Blog: https://github.com/pythonindia/inpycon-blog/pull/326

**Comment by Pradhvan** [comment]
Social Media Announcement 

___

We are delighted to announce EPAM(@EPAM_India) as Gold Sponsor for PyCon India 2020. 

Read more about EPAM in our blog 

blog link

#PyConIndia2020 

poster

cc: @sayanchowdhury @inovizz

**Comment by inovizz** [comment]
@Sc0rpi0n101 - Use this one https://user-images.githubusercontent.com/3849885/93663821-126f4600-fa88-11ea-982a-2d3feaba4843.png

**Comment by Pradhvan** [comment]
Announcement Post 
___

Twitter: https://twitter.com/pyconindia/status/1307280503398002689

LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:6713047963863707648

Facebook: https://www.facebook.com/133849919970392/posts/3617732171582132/

**Comment by Pradhvan** [comment]
Thank You everyone for helping in closing the issue. 😄
