### ISSUE TITLE
Announce Toyota Connected as SILVER SPONSOR

### ISSUE THREAD

**Issue by Pradhvan** [pythonindia/inpycon2020-tasks#88]
Scheduled: 9AM, 20 September

Sponsor Name: Toyota Connected

Sponsor Tier: Silver

Sponsor Website: http://www.toyotaconnected.co.in/
 
Sponsor Description:
Toyota Connected is enabling improved safety and convenience with a cloud-based digital connected mobility intelligence platform. We are leveraging vehicle data and artificial intelligence to change the way people interact with vehicles. We are a team of data scientists, engineers, and designers who share the vision of transforming Toyota from an automotive giant to a mobility company with cutting-edge technology. We work on improving people’s lives. This requires an insatiable curiosity about people. It also needs an amalgamation of passion, creativity, and innovation. We provide an inspiring environment for our teams to grow and be able to create smooth experiences for people. Millions of people around the world drive a Toyota or a Lexus. Our mission is to ensure that their drives are safer and more connected.

Sponsor Logo: <https://drive.google.com/file/d/18zywnITo8MJTAa8bY19WO1QONBS5-k5j/view?usp=sharing>

## Tasks
- [x] Social Media announcement @Pradhvan 
- [x] Blog post announcement @vipulgupta2048 
- [x] Website update to display sponsor logo  @palnabarun 

### Pre 12AM
- [x] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @Pradhvan 
- [x] Merge the website changes @palnabarun

### Post 9AM
- [x] Deploy the blog and the website @palnabarun 
- [x] Send the social media announcements out @Pradhvan

**Comment by Pradhvan** [comment]
Social Media Announcement
___

We are delighted to announce Toyota Connected(@toyota_tweet) as Silver Sponsor for PyCon India 2020. 

Read more about Toyota Connected in our blog.

blog link

#PyConIndia2020 

poster

cc: @inovizz

**Comment by inovizz** [comment]
Do we have the poster ready?

**Comment by Pradhvan** [comment]
@palnabarun can work on the poster.

**Comment by Pradhvan** [comment]
Link to poster: https://drive.google.com/file/d/1OfFP6iDHn8aMkleAWKNflVblXhVYOiSi/view

**Comment by rayandas** [comment]
Twitter: https://twitter.com/pyconindia/status/1307519721550434307?s=19

LinkedIn: https://www.linkedin.com/posts/pyconindia_pyconindia2020-activity-6713286102163296256-780m

Facebook: https://www.facebook.com/133849919970392/posts/3619833674705315/

**Comment by Pradhvan** [comment]
Thank you everyone in helping in closing the issue. 😀
