### ISSUE TITLE
Workshop schedule posts

### ISSUE THREAD

**Issue by Pradhvan** [pythonindia/inpycon2020-tasks#89]
- [ ]  A single post for each workshop i.e 7 workshop posts

- [ ] Send a workshop schedule post from the local user group's meetup page. 

- [ ] Cross-Post to social media channels about workshops.

**Comment by Pradhvan** [comment]
@inovizz for workshop poster beside the given fields below anything else would be required? 

- Title of the workshop

- Name of the speaker 

- Image of the speaker 


Reference Post: https://twitter.com/pyconfhyd/status/1202871049479569410

**Comment by inovizz** [comment]
@Pradhvan - sounds good.

**Comment by Pradhvan** [comment]
Images of the speaker received:


- [x]  Nabraun: Python on Kubernetes: A primer 

- [x] Anand S: Animating Data in PowerPoint 

- [x] David Tischler and Vipul Gupta: Containerizing Python and Deploying to IoT and Edge Devices 

- [x] Evan Smith: Getting started with Python

- [ ] Bhargav Srinivasa:  Python for Computational Social Science with Text, Networks and clever data games  

- [x] Anmol Jindal: Concurrency Patterns with Python 

- [x] Rumanu Bhardwaj : Meme Saheb - Using Dank Learning to Generate Original Meme Captions


Schedule for the workshop: https://in.pycon.org/2020/#schedule 

@noblebatman this it to track the info

**Comment by iamaravindsekar** [comment]
Hey folks, the posters can be found in the folder in this url, Thank You :)
[https://drive.google.com/drive/folders/1yv7t3ObUKtjiODH_VU-E-OWHHs8l_r8m?usp=sharing](url)
