### ISSUE TITLE
Create a ACL list to know who has access to what

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2020-tasks#9]

**Comment by palnabarun** [comment]
Access List is stored here at the moment. 

https://www.notion.so/pyconindia/3297b8a06a6f4152b9d00c8e2895422e?v=3ab15aefb69b4e5b82870d74f392d181

**Comment by palnabarun** [comment]
Initial access sheet had been created.

The ACL will be reiterated as planning progresses.
