### ISSUE TITLE
Social media posts about diversity events during PyCon India 

### ISSUE THREAD

**Issue by Pradhvan** [pythonindia/inpycon2020-tasks#90]

**Comment by sukanyamandal** [comment]
Hello team,

Need to schedule two post tonight (30/09/2020) - both twitter and linkedIn

**post 1 @ 8 p.m.** regarding PyLadies India Lunch (banner and description --> https://drive.google.com/drive/folders/1lo_Zr4fC0fC58NU3rp61oEzR2Ca4vapO?usp=sharing)
**post 2 @ 9 p.m.** on the diversity and inclusion track (banner and blog link --> https://drive.google.com/drive/folders/1PwXtvfEfi6gWaR0D2mXEXFi241HI_CV6?usp=sharing)

**Comment by Pradhvan** [comment]
@sukanyamandal closing the issue now.
