### ISSUE TITLE
Announce Red Hat as Silver SPONSOR

### ISSUE THREAD

**Issue by inovizz** [pythonindia/inpycon2020-tasks#91]
Scheduled: 22nd Sep 9:00 am

Sponsor Name: Red Hat

Sponsor Tier: Silver

Sponsor Website: https://www.redhat.com/en 

Sponsor Description:
Red Hat is the world's leading provider of enterprise open source software solutions, using a community-powered approach to deliver reliable and high-performing Linux, hybrid cloud, container, and Kubernetes technologies. Red Hat helps customers integrate new and existing IT applications, develop cloud-native applications, standardize on our industry-leading operating system, and automate, secure, and manage complex environments. Award-winning support, training, and consulting services make Red Hat a trusted adviser to the Fortune 500. As a strategic partner to cloud providers, system integrators, application vendors, customers, and open source communities, Red Hat can help organizations prepare for the digital future.

Sponsor Logo: https://pnt.redhat.com/pnt/p-11629415/Logo-RedHat-A-Color-RGB.png 

## Tasks
- [x] Social Media announcement @Pradhvan 
- [x] Blog post announcement @vipulgupta2048 
- [x] Website update to display sponsor logo  @palnabarun 

### Pre 12:00 AM
- [x] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @Pradhvan 
- [x] Merge the website changes @palnabarun
- [x] Deploy the blog and the website @palnabarun 

### At 9:00 AM
- [x] Send the social media announcements out @Pradhvan

**Comment by inovizz** [comment]
<img width="613" alt="Logo-RedHat-A-Color-RGB" src="https://user-images.githubusercontent.com/3849885/93752989-1a142380-fc1d-11ea-8fc6-365a57dc41f4.png">

**Comment by Sc0rpi0n101** [comment]
Blog: https://github.com/pythonindia/inpycon-blog/pull/330

**Comment by iamaravindsekar** [comment]
The announcement poster can be found in the following url, Thank You
[https://drive.google.com/file/d/15wTq9zRNWwl-JgnPs1tL4EoFrAwt4jHL/view?usp=sharing](url)

**Comment by Pradhvan** [comment]
Social Media Post Draft
---

We are excited to announce Red Hat(@RedHat) as Silver Sponsor for PyCon India 2020.

Read more about Red Hat in our blog.

Blog Link

#PyConIndia2020 

Poster Here

**Comment by rayandas** [comment]
Twitter: https://twitter.com/pyconindia/status/1308247563439452160?s=19

LinkedIn: https://www.linkedin.com/posts/pyconindia_pyconindia2020-activity-6714013578028032000-pQU9

Facebook: https://www.facebook.com/133849919970392/posts/3626146130740736/

**Comment by Pradhvan** [comment]
Thank You everyone for helping in closing the issue. 😄
