### ISSUE TITLE
Announce GitHub as Silver SPONSOR

### ISSUE THREAD

**Issue by inovizz** [pythonindia/inpycon2020-tasks#93]
Scheduled: 22nd Sep 5:00 PM

Sponsor Name: GitHub

Sponsor Tier: Silver

Sponsor Website: https://github.co/pyconin
 
Sponsor Description:
GitHub is a development platform inspired by the way you work. From open source to business, you can host and review code, manage projects, and build software alongside 50 million developers.
Automate from code to cloud using GitHub Actions, host your container images using GitHub Container Registry and bring GitHub collaboration tools to your small screens with a fully-native mobile and tablet experience with GitHub for mobile.
GitHub is home to the world’s largest community of developers and their projects - whether you’re making your first commit or sending a Rover to Mars, there’s room for you here, too.

Sponsor Logo: https://drive.google.com/file/d/1tvTgjr8XxsAmWGH5VIdsQ9JjKnJ1cj9j/view?usp=sharing

## Tasks
- [x] Social Media announcement @Pradhvan 
- [x] Blog post announcement @vipulgupta2048 
- [x] Website update to display sponsor logo  @palnabarun 

### Pre 4PM
- [x] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @Pradhvan 
- [x] Merge the website changes @palnabarun

### Post 5PM
- [x] Deploy the blog and the website @palnabarun 
- [x] Send the social media announcements out @Pradhvan

**Comment by vipulgupta2048** [comment]
Taking it up!

**Comment by iamaravindsekar** [comment]
The announcement media can be found in the drive url, Thank you :)
[https://drive.google.com/file/d/1ExSIW74RIwg8Ox6VJgKdmSqw_yt73ejQ/view?usp=sharing](url)

**Comment by Pradhvan** [comment]
Social Media Post Draft
---

We are excited to announce GitHub(@github) as Silver Sponsor for PyCon India 2020.

Read more about GitHub in our blog.

https://in.pycon.org/blog/2020/sponsor-announcement-github.html

#PyConIndia2020 

Poster Here

**Comment by Pradhvan** [comment]
Social Media Posts
---

LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:6714133526549213184

Twitter: https://twitter.com/pyconindia/status/1308367345954353152 

Facebook: https://www.facebook.com/PyConIndia/posts/3627126653976017

**Comment by Pradhvan** [comment]
Thank You everyone for helping in closing the issue.
