### ISSUE TITLE
Announce Microsoft Azure as platinum SPONSOR

### ISSUE THREAD

**Issue by inovizz** [pythonindia/inpycon2020-tasks#94]
Scheduled: 23rd Sep, 9:00 AM

Sponsor Name: Microsoft Azure

Sponsor Tier: Platinum

Sponsor Website: https://azure.microsoft.com/en-in/ (Hyperlinked to - https://azure.microsoft.com/en-us/?wt.mc_id=AID3022746_QSG_474804&ocid=AID3022746_QSG_474804&WT.mc_id=pyconindia-azure-cxa)
 
Sponsor Description:
Microsoft is the leading platform and company for the mobile-first, cloud-first world, and its mission is to empower every person and every organization on the planet to achieve more.

Microsoft has worked with Python communities to create tools and services which provide ease of development. This year at PyCon India, Microsoft is super excited to introduce two tracks at the Microsoft Learning Hub – Skilling and Community. The Skilling room is where you can skill-up your Cloud, Python, AI and Machine Learning knowledge. The Community room is the place to hear from the Community Leaders on both tech and non-tech topics.

Join us at the Microsoft Learning Hub at PyCon India 2020 to learn more about Microsoft Azure.

Sponsor Logo:
![azure](https://user-images.githubusercontent.com/3849885/93929791-04485080-fd3a-11ea-8c8f-b5246250ed79.png)

## Tasks
- [x] Social Media announcement @Pradhvan 
- [x] Blog post announcement @vipulgupta2048 
- [x] Website update to display sponsor logo  @palnabarun 

### Pre 12:00 AM
- [x] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @Pradhvan 
- [x] Merge the website changes @palnabarun
- [x] Deploy the blog and the website @palnabarun 

### At 9:00 AM
- [x] Send the social media announcements out @Pradhvan

**Comment by Sc0rpi0n101** [comment]
Blog: https://github.com/pythonindia/inpycon-blog/pull/333

**Comment by Pradhvan** [comment]
Draft 
---
We are excited to announce Microsoft Azure(@Azure) as Platinum Sponsor for PyCon India 2020.

Read more about Microsoft Azure in our blog.

Blog Link

#PyConIndia2020

Poster Here

cc: @inovizz

**Comment by iamaravindsekar** [comment]
The social media announcement poster can be found in the following url, Thank you
[https://drive.google.com/file/d/15OGGSt0RmoSIl2b4t-vZHsqsl05V06Zl/view?usp=sharing](url)

**Comment by rayandas** [comment]
Twitter: https://twitter.com/pyconindia/status/1308610762798034945?s=19

LinkedIn: https://www.linkedin.com/posts/pyconindia_pyconindia2020-activity-6714377768328663040-lhvT

Facebook: https://www.facebook.com/133849919970392/posts/3629367400418609/

**Comment by palnabarun** [comment]
Thanks everyone for shepherding this through. :smile:
