### ISSUE TITLE
Announce Pipal Academy as STARTUP SPONSOR

### ISSUE THREAD

**Issue by Pradhvan** [pythonindia/inpycon2020-tasks#96]
Scheduled: 24 September 

Sponsor Name: Pipal Academy

Sponsor Tier: STARTUP 

Sponsor Website: https://pipal.in/
 
Sponsor Description:

Pipal Academy is a collective of experienced technologists, who care deeply about the art of software development. We offer in-depth courses on niche technical topics.

We regularly conduct public workshops and also offer on site corporate trainings. Our courses are targeted at professional software developers and we make sure they are hands-on and interactive. Very often the participants finish our courses with a lot of excitement and joy of learning.

Sponsor Logo: 

![image](https://user-images.githubusercontent.com/13925830/93977867-c62e4980-fd98-11ea-9ff7-95cc04a871cc.png)

## Tasks
- [x] Social Media announcement @Pradhvan 
- [x] Blog post announcement @vipulgupta2048 
- [x] Website update to display sponsor logo  @palnabarun 

### Pre 4PM
- [x] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @Pradhvan 
- [x] Merge the website changes @palnabarun

### Post 5PM
- [x] Deploy the blog and the website @palnabarun 
- [x] Send the social media announcements out @Pradhvan

**Comment by Pradhvan** [comment]
@noblebatman the logo has been updated. Whenever you are free you can work on the poster.

**Comment by iamaravindsekar** [comment]
The announcement media can be found in the folder this url, Thanks
[https://drive.google.com/drive/folders/1PzrBgeXS4ofU04a_xflxqqhk9MFN1FOZ?usp=sharing](url)

**Comment by Pradhvan** [comment]
Social Media Posts:
---

LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:6714860041813446656

Twitter: https://twitter.com/pyconindia/status/1309093181200494594

Facebook: https://www.facebook.com/133849919970392/posts/3634039239951425/

**Comment by Pradhvan** [comment]
Thank You everyone for helping in closing the issue.
